--- # transfer file from local to remote server
- hosts: all
  become_user: yes
  gather_facts: no
  tasks:
    - copy:
        src: /Users/chennavarri/sanju/playbooks/done 
        dest: /Users/chennavarri/sanju/
