--- # LOOP Playbook example
- hosts: all
  user: local
  sudo: sudo
  connection: ssh
  gather_facts: no
  tasks: 
    - name: Add a list of users
      user: name={{ item }} state=present
      with_items:
