--- # UNTIL EXAMPLE AND HANDLER SECTION
- hosts: localhost
  become_user: yes
  gather_facts: no
  tasks:
    - name: Install Apache Web Server
      yum: pkg=httpd state=latest
    - name: Verify Service Status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5
    - debug: var=result
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
